-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE master.country (
  id integer NOT NULL,
  name character varying NOT NULL,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean NOT NULL,
  CONSTRAINT country_pkey PRIMARY KEY (id)
);
CREATE TABLE master.state (
  id bigint NOT NULL,
  name character varying NOT NULL,
  country_id integer NOT NULL,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean NOT NULL,
  state_code character varying DEFAULT '2'::character varying UNIQUE,
  CONSTRAINT state_pkey PRIMARY KEY (id),
  CONSTRAINT state_country_id_fkey FOREIGN KEY (country_id) REFERENCES master.country(id)
);
CREATE TABLE master.merchant (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  contact_person_name character varying NOT NULL,
  organization_name character varying,
  email character varying,
  phone_country_code integer,
  phone character varying,
  pan_number character varying,
  addressline1 character varying,
  addressline2 character varying,
  state bigint,
  pincode integer,
  country integer,
  gstn_state bigint,
  kyc_completed_sw boolean,
  kyc_completed_date timestamp without time zone,
  aadhaar_number character varying,
  agreement_signed_sw boolean,
  agreement_signed_date timestamp without time zone,
  db_connection character varying,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  gstn character varying,
  pan_docid character varying,
  aadhaar_docid character varying,
  gstn_docid character varying,
  organization_sw boolean,
  city character varying,
  brand_name character varying,
  contact_phone character varying,
  contact_email character varying,
  sin_number character varying,
  sin_docid character varying,
  tin_number character varying,
  tin_docid character varying,
  moa_docid character varying,
  aoa_docid character varying,
  trading_certificate_docid character varying,
  director_information_docid character varying,
  partnership_agreement_docid character varying,
  CONSTRAINT merchant_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_phone_country_code_fkey FOREIGN KEY (phone_country_code) REFERENCES master.country(id),
  CONSTRAINT merchant_state_fkey FOREIGN KEY (state) REFERENCES master.state(id),
  CONSTRAINT merchant_country_fkey FOREIGN KEY (country) REFERENCES master.country(id),
  CONSTRAINT merchant_gstn_state_fkey FOREIGN KEY (gstn_state) REFERENCES master.state(id)
);
CREATE TABLE master.merchant_service (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  merchant_id bigint NOT NULL,
  name character varying NOT NULL,
  logo_image_path character varying,
  single_qr_sw boolean,
  background_color character varying,
  beneficiary_name character varying,
  account_type character varying,
  bank_account_number character varying,
  bank_name character varying,
  branch_name character varying,
  bank_ifsc character varying,
  start_time time without time zone,
  end_time time without time zone,
  mon_working_sw boolean,
  tue_working_sw boolean,
  wed_working_sw boolean,
  thu_working_sw boolean,
  fri_working_sw boolean,
  sat_working_sw boolean,
  sun_working_sw boolean,
  addressline1 character varying,
  addressline2 character varying,
  state bigint,
  pincode integer,
  country integer,
  location_coordinates character varying,
  encrypted_url character varying,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  sgst numeric,
  cgst numeric,
  igst numeric,
  start_date date,
  end_date date,
  recurring_sw boolean DEFAULT true,
  city character varying,
  advance_booking_days numeric DEFAULT '0'::numeric,
  CONSTRAINT merchant_service_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_service_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT merchant_service_state_fkey FOREIGN KEY (state) REFERENCES master.state(id),
  CONSTRAINT merchant_service_country_fkey FOREIGN KEY (country) REFERENCES master.country(id)
);
CREATE TABLE master.ticket_timeslot (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  merchant_id bigint NOT NULL,
  ticket_category_id bigint,
  name character varying NOT NULL,
  start time without time zone NOT NULL,
  end time without time zone NOT NULL,
  total_ticket_count integer,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  merchant_service_id bigint,
  CONSTRAINT ticket_timeslot_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_timeslot_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT fk_ticket_timeslot_category FOREIGN KEY (ticket_category_id) REFERENCES master.ticket_category(id),
  CONSTRAINT ticket_timeslot_merchant_service_id_fkey FOREIGN KEY (merchant_service_id) REFERENCES master.merchant_service(id)
);
CREATE TABLE master.ticket_category (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  merchant_service_id bigint NOT NULL,
  name character varying NOT NULL,
  timeslot_id bigint,
  total_ticket_count integer,
  age_restriction_sw boolean,
  child_age_limit integer,
  free_age_limit integer,
  adult_price numeric NOT NULL,
  child_price numeric,
  special_instruction character varying,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  CONSTRAINT ticket_category_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_category_merchant_service_id_fkey FOREIGN KEY (merchant_service_id) REFERENCES master.merchant_service(id),
  CONSTRAINT ticket_category_timeslot_id_fkey FOREIGN KEY (timeslot_id) REFERENCES master.ticket_timeslot(id)
);
CREATE TABLE master.subscription (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  subscription_name character varying NOT NULL,
  validity_days integer NOT NULL,
  annual_fee integer NOT NULL,
  allowed_scanning_device integer,
  allowed_pos_device integer,
  allowed_staff_login integer,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  CONSTRAINT subscription_pkey PRIMARY KEY (id)
);
CREATE TABLE master.merchant_subscription (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  merchant_id bigint NOT NULL,
  subscription_id bigint,
  merchant_service_id bigint NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  ticket_encryption_key character varying,
  secret_key character varying,
  secret_value character varying,
  allowed_scanning_device integer,
  allowed_pos_device integer,
  allowed_staff_login integer,
  convinience_fee numeric,
  ticket_refund_sw boolean,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  CONSTRAINT merchant_subscription_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_subscription_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT merchant_subscription_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES master.subscription(id),
  CONSTRAINT merchant_subscription_merchant_service_id_fkey FOREIGN KEY (merchant_service_id) REFERENCES master.merchant_service(id)
);
CREATE TABLE master.user_type (
  id bigint NOT NULL,
  internal_sw boolean,
  name character varying NOT NULL,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  CONSTRAINT user_type_pkey PRIMARY KEY (id)
);
CREATE TABLE master.user (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  user_type_id bigint NOT NULL,
  merchant_id bigint,
  user_fname character varying NOT NULL,
  phone_country_code integer,
  phone character varying NOT NULL,
  email character varying,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  user_mname character varying,
  user_lname character varying,
  auth_uuid uuid,
  CONSTRAINT user_pkey PRIMARY KEY (id),
  CONSTRAINT user_user_type_id_fkey FOREIGN KEY (user_type_id) REFERENCES master.user_type(id),
  CONSTRAINT user_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT user_phone_country_code_fkey FOREIGN KEY (phone_country_code) REFERENCES master.country(id)
);
CREATE TABLE master.merchant_device (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_subscription_id bigint NOT NULL,
  merchant_service_id bigint NOT NULL,
  phone character varying NOT NULL,
  publisher_id character varying NOT NULL,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status_sw boolean,
  CONSTRAINT merchant_device_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_device_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT merchant_device_merchant_subscription_id_fkey FOREIGN KEY (merchant_subscription_id) REFERENCES master.merchant_subscription(id),
  CONSTRAINT merchant_device_merchant_service_id_fkey FOREIGN KEY (merchant_service_id) REFERENCES master.merchant_service(id)
);
CREATE TABLE master.merchant_service_holiday (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  update_date timestamp with time zone NOT NULL DEFAULT now(),
  update_by bigint NOT NULL,
  status_sw boolean,
  merchant_id bigint NOT NULL,
  merchant_service_id bigint NOT NULL,
  holiday_name character varying NOT NULL,
  holiday_date date NOT NULL,
  CONSTRAINT merchant_service_holiday_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_service_holiday_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT merchant_service_holiday_merchant_service_id_fkey FOREIGN KEY (merchant_service_id) REFERENCES master.merchant_service(id)
);
CREATE TABLE master.merchant_service_picture (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_dt timestamp with time zone NOT NULL DEFAULT now(),
  merchant_id bigint NOT NULL,
  service_id bigint NOT NULL,
  category_id bigint NOT NULL,
  picture_id character varying NOT NULL,
  status_sw boolean,
  CONSTRAINT merchant_service_picture_pkey PRIMARY KEY (id),
  CONSTRAINT merchant_service_picture_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT merchant_service_picture_service_id_fkey FOREIGN KEY (service_id) REFERENCES master.merchant_service(id),
  CONSTRAINT merchant_service_picture_category_id_fkey FOREIGN KEY (category_id) REFERENCES master.ticket_category(id)
);
CREATE TABLE master.merchant_service_voucher (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  merchant_id bigint NOT NULL,
  service_id bigint NOT NULL,
  voucher_code character varying NOT NULL,
  percentage numeric NOT NULL,
  start_date date NOT NULL,
  end_date date,
  status_sw boolean,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by bigint NOT NULL,
  CONSTRAINT merchant_service_voucher_pkey PRIMARY KEY (id)
);