-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE transaction.ticket (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  customer_phone character varying,
  customer_phone_code character varying,
  merchant_id bigint NOT NULL,
  merchant_service_id bigint NOT NULL,
  booking_date timestamp without time zone NOT NULL,
  email character varying,
  dob date,
  gstin character varying,
  address character varying,
  customer_name character varying,
  payment_mode character varying,
  transaction_date timestamp without time zone,
  transaction_reference character varying,
  bank_reference character varying,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  status character varying,
  ticket_category_id bigint,
  ticket_timeslot_id bigint,
  CONSTRAINT ticket_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT ticket_merchant_service_id_fkey FOREIGN KEY (merchant_service_id) REFERENCES master.merchant_service(id),
  CONSTRAINT ticket_ticket_category_id_fkey FOREIGN KEY (ticket_category_id) REFERENCES master.ticket_category(id),
  CONSTRAINT ticket_ticket_timeslot_id_fkey FOREIGN KEY (ticket_timeslot_id) REFERENCES master.ticket_timeslot(id)
);
CREATE TABLE transaction.ticket_detail (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  ticket_id bigint NOT NULL,
  ticket_category_id bigint NOT NULL,
  qr_code_string character varying NOT NULL,
  scanned_sw boolean,
  scanned_time timestamp without time zone,
  adult_count integer NOT NULL,
  child_count integer NOT NULL,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  ticket_number character varying,
  CONSTRAINT ticket_detail_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_detail_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES transaction.ticket(id),
  CONSTRAINT ticket_detail_ticket_category_id_fkey FOREIGN KEY (ticket_category_id) REFERENCES master.ticket_category(id)
);
CREATE TABLE transaction.invoice (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  invoice_number character varying NOT NULL,
  merchant_id bigint NOT NULL,
  merchant_service_id bigint NOT NULL,
  total_amount numeric NOT NULL,
  convinience_fee numeric,
  sgst numeric,
  cgst numeric,
  igst numeric,
  discount_value numeric,
  grand_total numeric NOT NULL,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  discount_percentage numeric DEFAULT '0'::numeric,
  voucher_id bigint,
  customer_id bigint,
  CONSTRAINT invoice_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_merchant_id_fkey FOREIGN KEY (merchant_id) REFERENCES master.merchant(id),
  CONSTRAINT invoice_merchant_service_id_fkey FOREIGN KEY (merchant_service_id) REFERENCES master.merchant_service(id)
);
CREATE TABLE transaction.invoice_detail (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  invoice_id bigint NOT NULL,
  ticket_id bigint NOT NULL,
  ticket_category_id bigint NOT NULL,
  adult_price numeric,
  child_price numeric,
  adult_count integer,
  child_count integer,
  total_amount numeric,
  update_by bigint NOT NULL,
  update_date timestamp without time zone NOT NULL,
  CONSTRAINT invoice_detail_pkey PRIMARY KEY (id),
  CONSTRAINT invoice_detail_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES transaction.invoice(id),
  CONSTRAINT invoice_detail_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES transaction.ticket(id),
  CONSTRAINT invoice_detail_ticket_category_id_fkey FOREIGN KEY (ticket_category_id) REFERENCES master.ticket_category(id)
);